export const FILTER_BY_RATING = "FILTER_BY_RATING";
export const FILTER_BY_BRANDS = "FILTER_B_BRANDS";
export const SORT_BY_ORDER = "SORT_BY_ORDER";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
