export const FILTER_BY_RATING = "FILTER_BY_RATING";
export const FILTER_BY_BRANDS = "FILTER_B_BRANDS";
export const SORT_BY_ASCENDING = "SORT_BY_ASCENDING";
export const SORT_BY_DESCENDING = "SORT_BY_DESCENDING";